### PR TITLE
Safety branch

### PR DESCRIPTION
**Pull request by jawndiego**

### CODE REVIEW

**Comment by salieflewis** [comment]
This is how you should be fetching the block number from the logs array. It was being fetched correctly, you just weren't looking for the data in the correct way!

`const blockNumber = transactionData ? transactionData[0]?.blockNumber : null`

cc: @jawndiego @0xTranqui

**Comment by jawndiego** [comment]
> This is how you should be fetching the block number from the logs array. It was being fetched correctly, you just weren't looking for the data in the correct way!
> 
> `const blockNumber = transactionData ? transactionData[0]?.blockNumber : null`
> 
> cc: @jawndiego @0xTranqui

ooooooo ty

**Comment by jawndiego** [comment]
@salieflewis please review <3

**Review by salieflewis — APPROVED** [review]
lgtm

**Pull request merged**
